export interface IAutorizaado {
    Age: number,
    DocType: number,
    EntityName: string,
    FingerPrint: any,
    Grade: string,
    IDAccount: number,
    IDPERSONA: string,
    Name1: string,
    Name2: string,
    Nit: number,
    PDF417Str: string,
    Password: string,
    Since: string,
    SurName1: string,
    SurName2: string,
    Surname1: string,
    Surname2: string,
    User: any,
    eMail: string,
}